# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pokedata',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/pokedata',
                'lib_path': 'pokedata'},
  'syms': {'pokedata.scrape': {}}}