# AUTOGENERATED! DO NOT EDIT! File to edit: ../Notebooks/00_Webscrapping/00_00_getting_stats.ipynb.

# %% auto 0
__all__ = []

# %% ../Notebooks/00_Webscrapping/00_00_getting_stats.ipynb 3
import re
import requests
from bs4 import BeautifulSoup

import pandas as pd
from fastcore.foundation import L
