# AUTOGENERATED! DO NOT EDIT! File to edit: ../../Notebooks/00_Webscrapping/00_02_getting_sprites.ipynb.

# %% auto 0
__all__ = ['build_df_sprites']

# %% ../../Notebooks/00_Webscrapping/00_02_getting_sprites.ipynb 3
import re
import requests
from bs4 import BeautifulSoup

import pandas as pd
from fastcore.foundation import L
from fastcore.xtras import Path
from fastcore.parallel import parallel
from fastprogress.fastprogress import progress_bar

# %% ../../Notebooks/00_Webscrapping/00_02_getting_sprites.ipynb 19
def get_sprites(row, # Row of a sprites table.
                ):
    tds = row.find_all("td")
    sprites = L([td.find("a")["href"] if td.find("a") is not None else None for td in tds[1:]])
    sprites.insert(0, tds[0].text)
    return sprites

# %% ../../Notebooks/00_Webscrapping/00_02_getting_sprites.ipynb 21
def build_df_sprites(link):
    index = []
    pokemon_name = link.split("/")[-1].split("#")[0]
    route = f"{home}/{link}"
    r_ = requests.get(route)
    soup_ = BeautifulSoup(r_.text, "html.parser")
    sprites_table = soup_.find("table", attrs={"class": "data-table sprites-table sprites-history-table"})
    sprites_header = L([th.text for th in sprites_table.find("thead").find_all("th")])
    sprites_header.map(lambda x: x.replace(" ", "_"))
    normal_row, shiny_row = sprites_table.find("tbody").find_all("tr")
    sprites_normal, sprites_shiny = get_sprites(normal_row), get_sprites(shiny_row)
    index.append((pokemon_name, sprites_normal[0]))
    index.append((pokemon_name, sprites_shiny[0]))
    df = pd.DataFrame([sprites_normal, sprites_shiny], columns=sprites_header, index=pd.MultiIndex.from_tuples(index, names=["Pokemon", "Type"]))
    df.drop("Type", axis=1, inplace=True)
    return df
